(cl:defpackage scara_velocity_kinematics-srv
  (:use )
  (:export
   "EE_TO_JOINT_VELOCITY"
   "<EE_TO_JOINT_VELOCITY-REQUEST>"
   "EE_TO_JOINT_VELOCITY-REQUEST"
   "<EE_TO_JOINT_VELOCITY-RESPONSE>"
   "EE_TO_JOINT_VELOCITY-RESPONSE"
   "JOINT_TO_EE_VELOCITY"
   "<JOINT_TO_EE_VELOCITY-REQUEST>"
   "JOINT_TO_EE_VELOCITY-REQUEST"
   "<JOINT_TO_EE_VELOCITY-RESPONSE>"
   "JOINT_TO_EE_VELOCITY-RESPONSE"
  ))

