(cl:defpackage scara_pd_controller-srv
  (:use )
  (:export
   "JOINTCONTROLREFERENCE"
   "<JOINTCONTROLREFERENCE-REQUEST>"
   "JOINTCONTROLREFERENCE-REQUEST"
   "<JOINTCONTROLREFERENCE-RESPONSE>"
   "JOINTCONTROLREFERENCE-RESPONSE"
  ))

