// Generated by gencpp from file scara_inverse_kinematics/poseJoints.msg
// DO NOT EDIT!


#ifndef SCARA_INVERSE_KINEMATICS_MESSAGE_POSEJOINTS_H
#define SCARA_INVERSE_KINEMATICS_MESSAGE_POSEJOINTS_H

#include <ros/service_traits.h>


#include <scara_inverse_kinematics/poseJointsRequest.h>
#include <scara_inverse_kinematics/poseJointsResponse.h>


namespace scara_inverse_kinematics
{

struct poseJoints
{

typedef poseJointsRequest Request;
typedef poseJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct poseJoints
} // namespace scara_inverse_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_inverse_kinematics::poseJoints > {
  static const char* value()
  {
    return "cabb4d8365c1affb33eb07e1622932fc";
  }

  static const char* value(const ::scara_inverse_kinematics::poseJoints&) { return value(); }
};

template<>
struct DataType< ::scara_inverse_kinematics::poseJoints > {
  static const char* value()
  {
    return "scara_inverse_kinematics/poseJoints";
  }

  static const char* value(const ::scara_inverse_kinematics::poseJoints&) { return value(); }
};


// service_traits::MD5Sum< ::scara_inverse_kinematics::poseJointsRequest> should match
// service_traits::MD5Sum< ::scara_inverse_kinematics::poseJoints >
template<>
struct MD5Sum< ::scara_inverse_kinematics::poseJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_inverse_kinematics::poseJoints >::value();
  }
  static const char* value(const ::scara_inverse_kinematics::poseJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_inverse_kinematics::poseJointsRequest> should match
// service_traits::DataType< ::scara_inverse_kinematics::poseJoints >
template<>
struct DataType< ::scara_inverse_kinematics::poseJointsRequest>
{
  static const char* value()
  {
    return DataType< ::scara_inverse_kinematics::poseJoints >::value();
  }
  static const char* value(const ::scara_inverse_kinematics::poseJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_inverse_kinematics::poseJointsResponse> should match
// service_traits::MD5Sum< ::scara_inverse_kinematics::poseJoints >
template<>
struct MD5Sum< ::scara_inverse_kinematics::poseJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_inverse_kinematics::poseJoints >::value();
  }
  static const char* value(const ::scara_inverse_kinematics::poseJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_inverse_kinematics::poseJointsResponse> should match
// service_traits::DataType< ::scara_inverse_kinematics::poseJoints >
template<>
struct DataType< ::scara_inverse_kinematics::poseJointsResponse>
{
  static const char* value()
  {
    return DataType< ::scara_inverse_kinematics::poseJoints >::value();
  }
  static const char* value(const ::scara_inverse_kinematics::poseJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_INVERSE_KINEMATICS_MESSAGE_POSEJOINTS_H
