// Generated by gencpp from file scara_velocity_kinematics/joint_to_ee_velocity.msg
// DO NOT EDIT!


#ifndef SCARA_VELOCITY_KINEMATICS_MESSAGE_JOINT_TO_EE_VELOCITY_H
#define SCARA_VELOCITY_KINEMATICS_MESSAGE_JOINT_TO_EE_VELOCITY_H

#include <ros/service_traits.h>


#include <scara_velocity_kinematics/joint_to_ee_velocityRequest.h>
#include <scara_velocity_kinematics/joint_to_ee_velocityResponse.h>


namespace scara_velocity_kinematics
{

struct joint_to_ee_velocity
{

typedef joint_to_ee_velocityRequest Request;
typedef joint_to_ee_velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct joint_to_ee_velocity
} // namespace scara_velocity_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocity > {
  static const char* value()
  {
    return "e127c5fbc297814596b68f3ef33853a2";
  }

  static const char* value(const ::scara_velocity_kinematics::joint_to_ee_velocity&) { return value(); }
};

template<>
struct DataType< ::scara_velocity_kinematics::joint_to_ee_velocity > {
  static const char* value()
  {
    return "scara_velocity_kinematics/joint_to_ee_velocity";
  }

  static const char* value(const ::scara_velocity_kinematics::joint_to_ee_velocity&) { return value(); }
};


// service_traits::MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocityRequest> should match
// service_traits::MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocity >
template<>
struct MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocity >::value();
  }
  static const char* value(const ::scara_velocity_kinematics::joint_to_ee_velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_velocity_kinematics::joint_to_ee_velocityRequest> should match
// service_traits::DataType< ::scara_velocity_kinematics::joint_to_ee_velocity >
template<>
struct DataType< ::scara_velocity_kinematics::joint_to_ee_velocityRequest>
{
  static const char* value()
  {
    return DataType< ::scara_velocity_kinematics::joint_to_ee_velocity >::value();
  }
  static const char* value(const ::scara_velocity_kinematics::joint_to_ee_velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocityResponse> should match
// service_traits::MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocity >
template<>
struct MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocity >::value();
  }
  static const char* value(const ::scara_velocity_kinematics::joint_to_ee_velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_velocity_kinematics::joint_to_ee_velocityResponse> should match
// service_traits::DataType< ::scara_velocity_kinematics::joint_to_ee_velocity >
template<>
struct DataType< ::scara_velocity_kinematics::joint_to_ee_velocityResponse>
{
  static const char* value()
  {
    return DataType< ::scara_velocity_kinematics::joint_to_ee_velocity >::value();
  }
  static const char* value(const ::scara_velocity_kinematics::joint_to_ee_velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_VELOCITY_KINEMATICS_MESSAGE_JOINT_TO_EE_VELOCITY_H
