// Generated by gencpp from file scara_velocity_kinematics/joint_to_ee_velocityRequest.msg
// DO NOT EDIT!


#ifndef SCARA_VELOCITY_KINEMATICS_MESSAGE_JOINT_TO_EE_VELOCITYREQUEST_H
#define SCARA_VELOCITY_KINEMATICS_MESSAGE_JOINT_TO_EE_VELOCITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_velocity_kinematics
{
template <class ContainerAllocator>
struct joint_to_ee_velocityRequest_
{
  typedef joint_to_ee_velocityRequest_<ContainerAllocator> Type;

  joint_to_ee_velocityRequest_()
    : th1(0.0)
    , th2(0.0)
    , d3(0.0)
    , th1_dot(0.0)
    , th2_dot(0.0)
    , d3_dot(0.0)  {
    }
  joint_to_ee_velocityRequest_(const ContainerAllocator& _alloc)
    : th1(0.0)
    , th2(0.0)
    , d3(0.0)
    , th1_dot(0.0)
    , th2_dot(0.0)
    , d3_dot(0.0)  {
  (void)_alloc;
    }



   typedef double _th1_type;
  _th1_type th1;

   typedef double _th2_type;
  _th2_type th2;

   typedef double _d3_type;
  _d3_type d3;

   typedef double _th1_dot_type;
  _th1_dot_type th1_dot;

   typedef double _th2_dot_type;
  _th2_dot_type th2_dot;

   typedef double _d3_dot_type;
  _d3_dot_type d3_dot;





  typedef boost::shared_ptr< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct joint_to_ee_velocityRequest_

typedef ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<std::allocator<void> > joint_to_ee_velocityRequest;

typedef boost::shared_ptr< ::scara_velocity_kinematics::joint_to_ee_velocityRequest > joint_to_ee_velocityRequestPtr;
typedef boost::shared_ptr< ::scara_velocity_kinematics::joint_to_ee_velocityRequest const> joint_to_ee_velocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator1> & lhs, const ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.th1 == rhs.th1 &&
    lhs.th2 == rhs.th2 &&
    lhs.d3 == rhs.d3 &&
    lhs.th1_dot == rhs.th1_dot &&
    lhs.th2_dot == rhs.th2_dot &&
    lhs.d3_dot == rhs.d3_dot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator1> & lhs, const ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_velocity_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94c0e53b96ae984787f7b524a794ee48";
  }

  static const char* value(const ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94c0e53b96ae9847ULL;
  static const uint64_t static_value2 = 0x87f7b524a794ee48ULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_velocity_kinematics/joint_to_ee_velocityRequest";
  }

  static const char* value(const ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 th1\n"
"float64 th2\n"
"float64 d3\n"
"float64 th1_dot\n"
"float64 th2_dot\n"
"float64 d3_dot\n"
;
  }

  static const char* value(const ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.th1);
      stream.next(m.th2);
      stream.next(m.d3);
      stream.next(m.th1_dot);
      stream.next(m.th2_dot);
      stream.next(m.d3_dot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_to_ee_velocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_velocity_kinematics::joint_to_ee_velocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "th1: ";
    Printer<double>::stream(s, indent + "  ", v.th1);
    s << indent << "th2: ";
    Printer<double>::stream(s, indent + "  ", v.th2);
    s << indent << "d3: ";
    Printer<double>::stream(s, indent + "  ", v.d3);
    s << indent << "th1_dot: ";
    Printer<double>::stream(s, indent + "  ", v.th1_dot);
    s << indent << "th2_dot: ";
    Printer<double>::stream(s, indent + "  ", v.th2_dot);
    s << indent << "d3_dot: ";
    Printer<double>::stream(s, indent + "  ", v.d3_dot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_VELOCITY_KINEMATICS_MESSAGE_JOINT_TO_EE_VELOCITYREQUEST_H
