// Generated by gencpp from file scara_velocity_controller/VelocityControlReference.msg
// DO NOT EDIT!


#ifndef SCARA_VELOCITY_CONTROLLER_MESSAGE_VELOCITYCONTROLREFERENCE_H
#define SCARA_VELOCITY_CONTROLLER_MESSAGE_VELOCITYCONTROLREFERENCE_H

#include <ros/service_traits.h>


#include <scara_velocity_controller/VelocityControlReferenceRequest.h>
#include <scara_velocity_controller/VelocityControlReferenceResponse.h>


namespace scara_velocity_controller
{

struct VelocityControlReference
{

typedef VelocityControlReferenceRequest Request;
typedef VelocityControlReferenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VelocityControlReference
} // namespace scara_velocity_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_velocity_controller::VelocityControlReference > {
  static const char* value()
  {
    return "a2dcd12186fef25175dd209ccf6b3de3";
  }

  static const char* value(const ::scara_velocity_controller::VelocityControlReference&) { return value(); }
};

template<>
struct DataType< ::scara_velocity_controller::VelocityControlReference > {
  static const char* value()
  {
    return "scara_velocity_controller/VelocityControlReference";
  }

  static const char* value(const ::scara_velocity_controller::VelocityControlReference&) { return value(); }
};


// service_traits::MD5Sum< ::scara_velocity_controller::VelocityControlReferenceRequest> should match
// service_traits::MD5Sum< ::scara_velocity_controller::VelocityControlReference >
template<>
struct MD5Sum< ::scara_velocity_controller::VelocityControlReferenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_velocity_controller::VelocityControlReference >::value();
  }
  static const char* value(const ::scara_velocity_controller::VelocityControlReferenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_velocity_controller::VelocityControlReferenceRequest> should match
// service_traits::DataType< ::scara_velocity_controller::VelocityControlReference >
template<>
struct DataType< ::scara_velocity_controller::VelocityControlReferenceRequest>
{
  static const char* value()
  {
    return DataType< ::scara_velocity_controller::VelocityControlReference >::value();
  }
  static const char* value(const ::scara_velocity_controller::VelocityControlReferenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_velocity_controller::VelocityControlReferenceResponse> should match
// service_traits::MD5Sum< ::scara_velocity_controller::VelocityControlReference >
template<>
struct MD5Sum< ::scara_velocity_controller::VelocityControlReferenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_velocity_controller::VelocityControlReference >::value();
  }
  static const char* value(const ::scara_velocity_controller::VelocityControlReferenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_velocity_controller::VelocityControlReferenceResponse> should match
// service_traits::DataType< ::scara_velocity_controller::VelocityControlReference >
template<>
struct DataType< ::scara_velocity_controller::VelocityControlReferenceResponse>
{
  static const char* value()
  {
    return DataType< ::scara_velocity_controller::VelocityControlReference >::value();
  }
  static const char* value(const ::scara_velocity_controller::VelocityControlReferenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_VELOCITY_CONTROLLER_MESSAGE_VELOCITYCONTROLREFERENCE_H
