(cl:defpackage scara_velocity_controller-srv
  (:use )
  (:export
   "VELOCITYCONTROLREFERENCE"
   "<VELOCITYCONTROLREFERENCE-REQUEST>"
   "VELOCITYCONTROLREFERENCE-REQUEST"
   "<VELOCITYCONTROLREFERENCE-RESPONSE>"
   "VELOCITYCONTROLREFERENCE-RESPONSE"
  ))

